const mongoose = require('mongoose');

const diplomaSchema = new mongoose.Schema({
    student: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    title: { type: String, required: true },
    institution: { type: String, required: true },
    issueDate: { type: Date, required: true },
    diplomaId: { type: String, unique: true },
    token: { type: String }, // Token to be generated by smart contract
});

module.exports = mongoose.model('Diploma', diplomaSchema);
